spring.application.name=secure-bank-api

spring.datasource.url=jdbc:postgresql://localhost:5433/secure_bank_db
spring.datasource.username=postgres
spring.datasource.password=Anshi
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=8081

app.jwt.secret=secure-bank-api-secret-key-secure-bank-api-secret-key
app.jwt.expiration-ms=86400000
